//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApprovals.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyApprovals.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Comment.
        /// </summary>
        public static string AddCommentText {
            get {
                return ResourceManager.GetString("AddCommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding comment to the order... Please wait!.
        /// </summary>
        public static string AddingCommentText {
            get {
                return ResourceManager.GetString("AddingCommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string AmountText {
            get {
                return ResourceManager.GetString("AmountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Approvals.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approving the order... Please wait!.
        /// </summary>
        public static string ApprovingText {
            get {
                return ResourceManager.GetString("ApprovingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments &amp; History.
        /// </summary>
        public static string CommentsHistoryText {
            get {
                return ResourceManager.GetString("CommentsHistoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to approve this order?.
        /// </summary>
        public static string ConfirmApproveText {
            get {
                return ResourceManager.GetString("ConfirmApproveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reject this order?.
        /// </summary>
        public static string ConfirmRejectText {
            get {
                return ResourceManager.GetString("ConfirmRejectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created At.
        /// </summary>
        public static string CreatedDateText {
            get {
                return ResourceManager.GetString("CreatedDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DateText {
            get {
                return ResourceManager.GetString("DateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailText {
            get {
                return ResourceManager.GetString("EmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network error or the server did not return response.
        /// </summary>
        public static string FailureText {
            get {
                return ResourceManager.GetString("FailureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Approve.
        /// </summary>
        public static string FinalApproveText {
            get {
                return ResourceManager.GetString("FinalApproveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Details.
        /// </summary>
        public static string ItemDetailsText {
            get {
                return ResourceManager.GetString("ItemDetailsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string ItemText {
            get {
                return ResourceManager.GetString("ItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading more orderrs... Please wait!.
        /// </summary>
        public static string LoadingMoreOrdersText {
            get {
                return ResourceManager.GetString("LoadingMoreOrdersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading order detail...Please wait!.
        /// </summary>
        public static string LoadingOrderDetailText {
            get {
                return ResourceManager.GetString("LoadingOrderDetailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading orders... Please wait!.
        /// </summary>
        public static string LoadingOrdersText {
            get {
                return ResourceManager.GetString("LoadingOrdersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load More.
        /// </summary>
        public static string LoadMoreText {
            get {
                return ResourceManager.GetString("LoadMoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in... Please wait!.
        /// </summary>
        public static string LoggingInText {
            get {
                return ResourceManager.GetString("LoggingInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LogoutText {
            get {
                return ResourceManager.GetString("LogoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Approver.
        /// </summary>
        public static string NextApproverText {
            get {
                return ResourceManager.GetString("NextApproverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OKText {
            get {
                return ResourceManager.GetString("OKText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional Approver.
        /// </summary>
        public static string OptionalApproverText {
            get {
                return ResourceManager.GetString("OptionalApproverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Approval.
        /// </summary>
        public static string OrderApprovalText {
            get {
                return ResourceManager.GetString("OrderApprovalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Details.
        /// </summary>
        public static string OrderDetailsText {
            get {
                return ResourceManager.GetString("OrderDetailsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordered By.
        /// </summary>
        public static string OrderedByText {
            get {
                return ResourceManager.GetString("OrderedByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Summary.
        /// </summary>
        public static string OrderSummaryText {
            get {
                return ResourceManager.GetString("OrderSummaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordText {
            get {
                return ResourceManager.GetString("PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Approvals.
        /// </summary>
        public static string Pivot1Title {
            get {
                return ResourceManager.GetString("Pivot1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Pivot2Title {
            get {
                return ResourceManager.GetString("Pivot2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QTY:.
        /// </summary>
        public static string QuantityText {
            get {
                return ResourceManager.GetString("QuantityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejecting the order... Please wait!.
        /// </summary>
        public static string RejectingText {
            get {
                return ResourceManager.GetString("RejectingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Order.
        /// </summary>
        public static string RejectText {
            get {
                return ResourceManager.GetString("RejectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string ReloadText {
            get {
                return ResourceManager.GetString("ReloadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveText {
            get {
                return ResourceManager.GetString("SaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Approvers.
        /// </summary>
        public static string SelectApproversText {
            get {
                return ResourceManager.GetString("SelectApproversText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allow to set Store URLempty.
        /// </summary>
        public static string StoreURLEmptyText {
            get {
                return ResourceManager.GetString("StoreURLEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store URL.
        /// </summary>
        public static string StoreURLText {
            get {
                return ResourceManager.GetString("StoreURLText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        public static string SubtotalText {
            get {
                return ResourceManager.GetString("SubtotalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOM:.
        /// </summary>
        public static string UomText {
            get {
                return ResourceManager.GetString("UomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating order detail... Please wait!.
        /// </summary>
        public static string UpdatingOrderText {
            get {
                return ResourceManager.GetString("UpdatingOrderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Comment.
        /// </summary>
        public static string YourCommentText {
            get {
                return ResourceManager.GetString("YourCommentText", resourceCulture);
            }
        }
    }
}
